### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: FB is not defined

### ISSUE THREAD

**Issue by suranan** [zyramedia/ng2-facebook-sdk#38]
Hello,

I got some error like this 

EXCEPTION: Uncaught (in promise): Error: Error in :0:0 caused by: FB is not defined
Error: Error in :0:0 caused by: FB is not defined
    at ViewWrappedError.ZoneAwareError (http://localhost:4200/vendor.bundle.js:111699:33)
    at ViewWrappedError.BaseError [as constructor] (http://localhost:4200/vendor.bundle.js:6905:16)
    at ViewWrappedError.WrappedError [as constructor] (http://localhost:4200/vendor.bundle.js:6970:16)
    at new ViewWrappedError (http://localhost:4200/vendor.bundle.js:61930:16)
    at CompiledTemplate.proxyViewClass.DebugAppView._rethrowWithContext (http://localhost:4200/vendor.bundle.js:85422:23)
    at CompiledTemplate.proxyViewClass.DebugAppView.createHostView (http://localhost:4200/vendor.bundle.js:85339:18)
    at ComponentFactory.create (http://localhost:4200/vendor.bundle.js:44860:25)
    at ViewContainerRef_.createComponent (http://localhost:4200/vendor.bundle.js:62606:62)
    at RouterOutlet.activate (http://localhost:4200/vendor.bundle.js:68452:40)
    at ActivateRoutes.placeComponentIntoOutlet (http://localhost:4200/vendor.bundle.js:25879:16)
    at ActivateRoutes.activateRoutes (http://localhost:4200/vendor.bundle.js:25846:26)
    at http://localhost:4200/vendor.bundle.js:25782:58
    at Array.forEach (native)
    at ActivateRoutes.activateChildRoutes (http://localhost:4200/vendor.bundle.js:25782:29)
    at ActivateRoutes.activate (http://localhost:4200/vendor.bundle.js:25756:14)

my step to install are

1. nstall via NPM
2.Add the Facebook JavaScript SDK to your index.html

and my example code are
`import { Component, OnInit } from '@angular/core';
import { FacebookService, FacebookLoginResponse, FacebookInitParams } from 'ng2-facebook-sdk/dist';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss'],
  providers: [FacebookService]
})
export class LoginComponent implements OnInit {

  constructor(private fb: FacebookService) {
    let fbParams: FacebookInitParams = {
      appId: '*****',
      xfbml: true,
      version: 'v2.8'
    };
    fb.init(fbParams);
  }

  onFacebookLoginClick(): void {
    this.fb.login().then(
      (response: FacebookLoginResponse) => console.log(response),
      (error: any) => console.log(error)
    );
  }`

thank you.

**Comment by ihadeed** [comment]
You need to add the Facebook JavaScript SDK to your `index.html` BEFORE your app's script. See https://github.com/zyramedia/ng2-facebook-sdk#installation.

**Comment by suranan** [comment]
thank you.
